encoding: utf-8
baseurl: "/"

url: 'https://betterdocs.herokuapp.com'

collections:
  pages:
    output: true
    permalink: /:slug

default_lang: 'en'
languages: [
  'en',
  'bg', 'bn',
  'cn',
  'de',
  'el', 'es',
  'fr',
  'hi', 
  'id', 'it',
  'ja',
  'ko',
  'ms',
  'pl', 'pt',
  'ro',
  'ru',
  'th', 'tr',
  'vi'
]

timezone: Europe/Moscow
exclude_from_localizations: ['javascript', 'images', 'css']

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap
