encoding: utf-8

url: http://localhost:4000

baseurl: /
format: ''

collections:
  pages:
    output: true
    permalink: /:slug

default_lang: 'en'
languages: [
  'en',
  'bg', 'bn',
  'cn',
  'de',
  'el', 'es',
  'fr',
  'hi', 
  'id', 'it',
  'ja',
  'ko',
  'ms',
  'pl', 'pt',
  'ro',
  'ru',
  'th',
  'tr',
  'vi'
]

locales:
  - {locale: en, name: English, flag: us}
  - {locale: bg, name: Български, flag: bg}
  - {locale: bn, name: বাঙালি, flag: bn}
  - {locale: cn, name: 中文, flag: cn}
  - {locale: de, name: Deutsche, flag: de}
  - {locale: el, name: Ελληνικά, flag: gr}
  - {locale: es, name: Español, flag: es}
  - {locale: fr, name: Français, flag: fr}
  - {locale: hi, name: हिंदी, flag: in}
  - {locale: id, name: Bahasa, flag: id}
  - {locale: it, name: Italiano, flag: it}
  - {locale: ja, name: 日本人, flag: jp}
  - {locale: ko, name: 한국어, flag: kr}
  - {locale: ms, name: Melayu, flag: ms}
  - {locale: pl, name: Polskie, flag: pl}
  - {locale: pt, name: Português, flag: es}
  - {locale: ro, name: Română, flag: ro}
  - {locale: ru, name: Русский, flag: ru}
  - {locale: th, name: ไทย, flag: th}
  - {locale: tr, name: Türk, flag: tr}
  - {locale: vi, name: Tiếng Việt, flag: vi}

timezone: Europe/Moscow
exclude_from_localizations: [
  'assets',
  'css',
  'fonts',
  'images',
  'javascripts',
  'CODE_OF_CONDUCT.md',
  'CONTRIBUTING.md',
  'Procfile',
  'Rakefile',
  'Vagrantfile',
  'README.md',
  'config.ru',
  'favicon.ico',
  'feed.xml',
  'sitemap.xml',
  'language.yml',
  'package.json',
  'static.json',
  'npm-shrinkwrap.json',
  'robots.txt',
  'ubuntu-bionic-18.04-cloudimg-console.log',
  '500.html'
]

allowed: [
  'css',
  'fonts',
  'images',
  'javascripts',
  'favicon.ico',
  'robots.txt',
  'sitemap.xml',
]

markdown: kramdown
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap
